rm(list=ls())
library(pracma)
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Control pseudowords and their ref words are not in same block (LD task)
# - Export XLS file formmatted for Gorilla(indicating block etc)
# - This version generates multiple columns that will be randomised btw subjcts
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v3/LD_10items/'
databasefile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
diroutput <- 'V:/spinco_data/SINON/Spreadsheets/LD/'
setwd(dirinput)

# search files and concat
database <- openxlsx::read.xlsx(databasefile,sheet = 'Merged')
# SNR assignments to file suffices
snrs_voco <- c('0.7p','0.75p','0.8p','0.85p','0.9p')
snrs_sissn <- c('-10db','-7.5db','-5db','-2.5db','0db')

# Create design temple to fill in later
snrs <- as.numeric(c(1,2,3,4,5))
noise <-  c('nv','sissn')
subset <- letters[1:(4*length(snrs))]

df <- as.data.frame(subset)
rots <- list()
for (i in 1:5) {
  if (i ==1){
    rots[[i]] <- paste0('NV_',snrs)
  } else {
    rots[[i]] <-  circshift(rots[[i-1]],1)
  }
  
}

rots <- do.call(rbind,rots)
rots1 <- rbind(gsub('NV_','SSN_',rots),rots)
rots2 <- rbind(rots,gsub('NV_','SSN_',rots))

colnames(rots1) <- paste0('list_A',1:5)
colnames(rots2) <- paste0('list_B',1:5)

refTab <- cbind(df,rots1,rots2)


########################################################################################
#-------------------------------------------------------------------------------

# LEXICAL DECISION 
#----------------------------
allNamesTab <- list()
allNamesTab_pseudo <- list()
for (i in 1:length(refTab$subset)){
  fileinput <- paste0('list2match10_set',i,'.txt')
  tab <- read.delim(fileinput,header = FALSE)  
  items <- tab$V1 
  pseudos <- gsub('-','',database$Pseudoword[which(database$CORRECT_SPELL %in% items)])
  
  
  specs <- refTab[i,][-1]
  specs <-  gsub('SSN_1$',paste0('SiSSN_norm',snrs_sissn[1],'.wav'),specs)
  specs <-  gsub('SSN_2$',paste0('SiSSN_norm',snrs_sissn[2],'.wav'),specs)
  specs <-  gsub('SSN_3$',paste0('SiSSN_norm',snrs_sissn[3],'.wav'),specs)
  specs <-  gsub('SSN_4$',paste0('SiSSN_norm',snrs_sissn[4],'.wav'),specs)
  specs <-  gsub('SSN_5$',paste0('SiSSN_norm',snrs_sissn[5],'.wav'),specs)
  specs <-  gsub('NV_1$',paste0('NV_norm_',snrs_voco[1],'.wav'),specs)
  specs <-  gsub('NV_2$',paste0('NV_norm_',snrs_voco[2],'.wav'),specs)
  specs <-  gsub('NV_3$',paste0('NV_norm_',snrs_voco[3],'.wav'),specs)
  specs <-  gsub('NV_4$',paste0('NV_norm_',snrs_voco[4],'.wav'),specs)
  specs <-  gsub('NV_5$',paste0('NV_norm_',snrs_voco[5],'.wav'),specs)
  
  namesTab <- list()
  namesTab_pseudo <- list()
  for (ii in 1:length(items)){
    namesTab[[ii]] <- gsub('_norm',paste0('_',items[ii],'_norm'),specs)
    namesTab_pseudo[[ii]] <- gsub('_norm',paste0('_',pseudos[ii],'_norm'),specs)
    
  }
  namesTab <- do.call(rbind,namesTab)
  namesTab_pseudo <- do.call(rbind,namesTab_pseudo)
  
  allNamesTab[[i]] <- namesTab
  allNamesTab_pseudo[[i]] <- namesTab_pseudo
}

allNamesTab <- as.data.frame(do.call(rbind,allNamesTab))
colnames(allNamesTab)<- colnames(refTab)[-1]
allNamesTab$block <-  rep(c(1,2,3,4),each=50)
allNamesTab$answer <-'word'


allNamesTab_pseudo <- as.data.frame(do.call(rbind,allNamesTab_pseudo))
colnames(allNamesTab_pseudo)<- colnames(refTab)[-1]
allNamesTab_pseudo$block <-  rep(c(3,4,1,2),each=50)
allNamesTab_pseudo$answer <-'pseudo'

#

# Formatting
tab2save <- rbind(allNamesTab,allNamesTab_pseudo)
tab2save <- tab2save[order(tab2save$block),]

tab2save$item <- sapply(strsplit(split ='_',tab2save$list_A1),'[[',2)
tab2save <- dplyr::relocate(tab2save, answer)
tab2save <- dplyr::relocate(tab2save, item)
tab2save <- dplyr::relocate(tab2save, block)


#
setwd(diroutput)
openxlsx::write.xlsx(tab2save,paste0(diroutput,'/Spreadsheets_LD.xlsx'))

# 