rm(list=ls())
library(pracma)
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Export XLS file formmatted for Gorilla(indicating block etc)
# - This version generates multiple columns that will be randomised btw subjcts
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v3/2FC_12items/'
databasefile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
sel <- openxlsx::read.xlsx('V:/spinco_data/LIRI_database/LIRI_database_subsets/2FC_postselection_ZH_AS_GFG.xlsx') # table with neighbors 

diroutput <- 'V:/spinco_data/SINON/Spreadsheets/2FC/'
setwd(dirinput)

# search files and concat
database <- openxlsx::read.xlsx(databasefile,sheet = 'Merged')
# SNR assignments to file suffices
snrs_voco <- c('0.7p','0.75p','0.8p','0.85p','0.9p')
snrs_sissn <- c('-10db','-7.5db','-5db','-2.5db','0db')

# Create design temple to fill in later
snrs <- as.numeric(c(1,2,3,4,5))
noise <-  c('nv','sissn')
subset <- letters[1:20]

df <- as.data.frame(subset)
rots <- list()
for (i in 1:5) {
  if (i ==1){
    rots[[i]] <- paste0('NV_',snrs)
  } else {
    rots[[i]] <-  circshift(rots[[i-1]],1)
  }
  
}

rots <- do.call(rbind,rots)
rots1 <- rbind(gsub('NV_','SSN_',rots),rots)
rots2 <- rbind(rots,gsub('NV_','SSN_',rots))

colnames(rots1) <- paste0('list_A',1:5)
colnames(rots2) <- paste0('list_B',1:5)

refTab <- cbind(df,rots1,rots2)


########################################################################################

########################################################################################################
# 2 FC task 
#----------------------------
setwd(dirinput)
allNamesTab <- list()
for (i in 1:length(refTab$subset)){
  fileinput <- paste0('list2match12_set',i,'.txt')
  tab <- read.delim(fileinput,header = FALSE)
  items <- tab$V1
  
  specs <- refTab[i,][-1]
  specs <-  gsub('SSN_1$',paste0('SiSSN_norm',snrs_sissn[1],'.wav'),specs)
  specs <-  gsub('SSN_2$',paste0('SiSSN_norm',snrs_sissn[2],'.wav'),specs)
  specs <-  gsub('SSN_3$',paste0('SiSSN_norm',snrs_sissn[3],'.wav'),specs)
  specs <-  gsub('SSN_4$',paste0('SiSSN_norm',snrs_sissn[4],'.wav'),specs)
  specs <-  gsub('SSN_5$',paste0('SiSSN_norm',snrs_sissn[5],'.wav'),specs)
  specs <-  gsub('NV_1$',paste0('NV_norm_',snrs_voco[1],'.wav'),specs)
  specs <-  gsub('NV_2$',paste0('NV_norm_',snrs_voco[2],'.wav'),specs)
  specs <-  gsub('NV_3$',paste0('NV_norm_',snrs_voco[3],'.wav'),specs)
  specs <-  gsub('NV_4$',paste0('NV_norm_',snrs_voco[4],'.wav'),specs)
  specs <-  gsub('NV_5$',paste0('NV_norm_',snrs_voco[5],'.wav'),specs)
  
  namesTab <- list()
  for (ii in 1:length(items)){
    namesTab[[ii]] <- gsub('_norm',paste0('_',items[ii],'_norm'),specs)
    
  }
  namesTab <- as.data.frame(do.call(rbind,namesTab))
  
  # add targets
  namesTab$item_target <- items
  namesTab$item_distractor <- sel$Final_distractor[Filter(function(x) !is.na(x), match(namesTab$item_target,sel$target))]
  
  # add position info, flip half of then 
  randomhalf <- sample(1:nrow(namesTab))[1:(nrow(namesTab)/2)]
  namesTab$item_left <- namesTab$item_target
  namesTab$item_left[randomhalf] <- namesTab$item_distractor[randomhalf]
  
  namesTab$item_right <- namesTab$item_distractor
  namesTab$item_right[randomhalf] <- namesTab$item_target[randomhalf]
  
  namesTab$correctAnswer <- 'left'
  namesTab$correctAnswer[randomhalf] <- 'right'
  
  #Add to longer array 
  allNamesTab[[i]] <- namesTab
  
}

allNamesTab <- as.data.frame(do.call(rbind,allNamesTab))
colnames(allNamesTab)[1:10] <- colnames(refTab)[-1]
allNamesTab$block <- rep(c(1,2,3,4),each=60)
 
# Formatting
tab2save <- allNamesTab
tab2save <- tab2save[order(tab2save$block),]
 
tab2save <- dplyr::relocate(tab2save, item_target)
tab2save <- dplyr::relocate(tab2save, item_distractor)
tab2save <- dplyr::relocate(tab2save, item_right)
tab2save <- dplyr::relocate(tab2save, item_left)
tab2save <- dplyr::relocate(tab2save, correctAnswer)
tab2save <- dplyr::relocate(tab2save, block)

#
setwd(diroutput)
openxlsx::write.xlsx(tab2save,paste0(diroutput,'/Spreadsheets_2FC.xlsx'))

