rm(list=ls())
library(pracma)
library(dplyr)
library(tidyr)
###############################################################################
# SPREADSHEETS TO USE IN GORILLA
# ----------------------------------------------------------------------------
# - Read subsets of items generated by MATCH
# - Assign balanced SNR levels
# - Control pseudowords and their ref words are not in same block (LD task)
# - Export XLS file formmatted for Gorilla(indicating block etc)
# - This version generates multiple columns that will be randomised btw subjcts
###############################################################################

# directories 
dirinput <- 'V:/spinco_data/LIRI_database/SINON_MATCH_v3/PM_20items/'
databasefile <-'V:/spinco_data/LIRI_database/LIRI_database_stimuli.xlsx'
diroutput <- 'V:/spinco_data/SINON/Spreadsheets/PM/'
setwd(dirinput)

# search files and concat
database <- openxlsx::read.xlsx(databasefile,sheet = 'Merged')
# SNR assignments to file suffices
snrs_voco <- c('0.7p','0.75p','0.8p','0.85p','0.9p')
snrs_sissn <- c('-10db','-7.5db','-5db','-2.5db','0db')

# Create design temple to fill in later
snrs <- as.numeric(c(1,2,3,4,5))
noise <-  c('nv','sissn')
subset <- letters[1:20]

df <- as.data.frame(subset)
rots <- list()
for (i in 1:5) {
  if (i ==1){
    rots[[i]] <- paste0('NV_',snrs)
  } else {
    rots[[i]] <-  circshift(rots[[i-1]],1)
  }
  
}

rots <- do.call(rbind,rots)
rots1 <- rbind(gsub('NV_','SSN_',rots),rots)
rots2 <- rbind(rots,gsub('NV_','SSN_',rots))

colnames(rots1) <- paste0('list_A',1:5)
colnames(rots2) <- paste0('list_B',1:5)

refTab <- cbind(df,rots1,rots2)


########################################################################################

########################################################################################################
# Picture matching
#----------------------------
setwd(dirinput)
allNamesTab <- list()
for (i in 1:length(refTab$subset)){
  fileinput <- paste0('list2match20_set',i,'.txt')
  tab <- read.delim(fileinput,header = FALSE)
  items <- tab$V1


  specs <- refTab[i,][-1]
  specs <-  gsub('SSN_1$',paste0('SiSSN_norm',snrs_sissn[1],'.wav'),specs)
  specs <-  gsub('SSN_2$',paste0('SiSSN_norm',snrs_sissn[2],'.wav'),specs)
  specs <-  gsub('SSN_3$',paste0('SiSSN_norm',snrs_sissn[3],'.wav'),specs)
  specs <-  gsub('SSN_4$',paste0('SiSSN_norm',snrs_sissn[4],'.wav'),specs)
  specs <-  gsub('SSN_5$',paste0('SiSSN_norm',snrs_sissn[5],'.wav'),specs)
  specs <-  gsub('NV_1$',paste0('NV_norm_',snrs_voco[1],'.wav'),specs)
  specs <-  gsub('NV_2$',paste0('NV_norm_',snrs_voco[2],'.wav'),specs)
  specs <-  gsub('NV_3$',paste0('NV_norm_',snrs_voco[3],'.wav'),specs)
  specs <-  gsub('NV_4$',paste0('NV_norm_',snrs_voco[4],'.wav'),specs)
  specs <-  gsub('NV_5$',paste0('NV_norm_',snrs_voco[5],'.wav'),specs)

  namesTab <- list()
  for (ii in 1:length(items)){
    namesTab[[ii]] <- gsub('_norm',paste0('_',items[ii],'_norm'),specs)

  }
  namesTab <- as.data.frame(do.call(rbind,namesTab))
  #picture <- database$PICTURE[which(database$CORRECT_SPELL %in% items )]  

  
  namesTab$match <- c(rep(1,nrow(namesTab)/2),rep(0,nrow(namesTab)/2)) %>% sample()
  allNamesTab[[i]] <- namesTab
}

allNamesTab <- as.data.frame(do.call(rbind,allNamesTab))
colnames(allNamesTab)<- c(colnames(refTab)[-1],'match')
allNamesTab$block <- rep(c(1,2,3,4),each=100)
 



# Additional info and Formatting
tab2save <- allNamesTab
tab2save <- tab2save[order(tab2save$block),]
tab2save$item <- sapply(strsplit(split ='_',tab2save$list_A1),'[[',2)

# Add matching and not matching pictures
tab2save$picture <- ''
for (p in 1:nrow(tab2save)){
  tab2save$picture[p] <- database$PICTURE[which(database$CORRECT_SPELL == tab2save$item[p])]    
}

    # shuffle the pictures for the trials marked as not a match
    original  <- tab2save$picture[which(tab2save$match==0)]
    replacement <- sample(original)
    while (length(which(original==replacement)>0)!=0) {# shuffle again until no name repeats position 
     replacement <- sample(original)
    } 
    tab2save$picture[tab2save$match==0] <- replacement
 
tab2save <- dplyr::relocate(tab2save, match)
tab2save <- dplyr::relocate(tab2save, picture)
tab2save <- dplyr::relocate(tab2save, item)
tab2save <- dplyr::relocate(tab2save, block)




#
setwd(diroutput)
openxlsx::write.xlsx(tab2save,paste0(diroutput,'/Spreadsheets_PM.xlsx'))
